input validation

diff --git a/.github/workflows/reusable-workflow-docker-image.yml b/.github/workflows/reusable-workflow-docker-image.yml
--- a/.github/workflows/reusable-workflow-docker-image.yml
+++ b/.github/workflows/reusable-workflow-docker-image.yml
@@ -11,10 +11,7 @@ on:
         type: string
       platform:
         required: true
-        type: choice
-        options:
-          - amd64
-          - arm64
+        type: string
 
 jobs:
   docker-build:
@@ -30,6 +27,14 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
+
+      - name: Input Validation
+        run: |
+          if [[ "${{ github.event.inputs.platform }}" != "amd64" ]] && \
+             [[ "${{ github.event.inputs.platform }}" != "arm64" ]]; then
+            echo "Invalid environment: ${{ github.event.inputs.platform }}"
+            exit 1
+          fi
 
       - name: Log in to Azure Container Registry
         uses: azure/docker-login@v1
@@ -71,8 +76,8 @@ jobs:
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: my-artifacts
-          path: build-artifacts
+          name: build-artifacts
+          path: build-artifacts/*
 
       - name: Tag and push Docker image as latest
         # if: github.ref == 'refs/heads/main' # TODO: uncomment once we are done with development
